name: "S3 Sync with cloudfront cache invalidation"
description: "Sync a directory to an AWS S3 repository and invalidate cloudfront cache"
author: TimekillerTK
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
